config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  # root "application#hello"
  root "pages#home"
  get '/about', to: 'pages#about'
  get '/help-page', to: 'pages#help_page'

  resources :todos
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :descriptions, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render plain: "Hello everyone!"
  end   
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  def home
    
  end   

  def about

  end

  def help_page

  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only:[:edit, :update, :show, :destroy]
  
  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.create(todo_params) 
    if @todo.save
      flash[:notice] = "Todo was created successfully!"
      redirect_to todo_path(@todo) 
    else
      render 'new'
    end  
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = "Todo was successfully updated"
      redirect_to todo_path(todo)
    else
      render 'edit'
    end  
  end

  def index
    @todo = Todo.all
  end

  def destroy
    @todo.destroy
    flash[:notice] = "Todo was deleted successfully"
    redirect_to todos_path
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :descriptions)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%= flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

app/views/pages/help_page.html.erb
<h1>Q&A</h1>
<%= image_tag ("grapefruit.png") %>

app/views/pages/home.html.erb
<h1>Hello world!</h1>
<h2>Test</h2>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h2>The following errors prevented the todo from being saved</h2>
<ul>
  <% @todo.errors.full_messages.each do |msg| %>
    <li><%= msg %></li> 
  <% end %>  
</ul>
<% end %>  

<%= form_for @todo do |todo_form| %>
  <p>
    <%= todo_form.label :name %><br>
    <%= todo_form.text_field :name %>
  </p>
  <p>
    <%= todo_form.label :descriptions %><br>
    <%= todo_form.text_area :descriptions %>
  </p>
  <p>
    <%= todo_form.submit %><br>
  </p>
<% end %>  

<%= link_to "Back to todos listing", todos_path %>

app/views/todos/edit.html.erb
<h1>Edit an existing Todo</h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Listing all Todos</h1>

<p>
  <%= link_to "Create a Todo", new_todo_path %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @todo.each do |todo| %>
    <tr>
      <td><%= todo.name %></td>
      <td><%= todo.descriptions %></td>
      <td><%= link_to "Edit", edit_todo_path(todo) %></td>
      <td><%= link_to "Show", todo_path(todo) %></td>
      <td><%= link_to "Delete", todo_path(todo), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
    </tr> 
  <% end %>   
</table>

app/views/todos/new.html.erb
<h1>Create a new Todo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Showing a Todo</h1>
<p>
  name: <%= @todo.name %>
</p>
<p>
  descriptions: <%= @todo.descriptions %>
</p>
<%= link_to "Edit this todo", edit_todo_path(@todo) %> |
<%= link_to "Back to todos listing", todos_path %>